### ISSUE TITLE
[enhancement] Add additional information to git branch (hash,parent hash,date, objecttype)

### ISSUE THREAD

**Issue by fcbry** [StartAutomating/ugit#230]
Hi, I'd like to add additional information to the `git branch` command, but I'm not sure how to do so, or where in `ugit` I could patch in support, any guidance appreciated.

To illustrate what I'd like to do consider the following. 

```
$b0 = (git branch --format "%(refname:short)|%(objectname)|%(parent)|%(committerdate:iso8601)|%(objecttype)")[0]
```
```
$b0.ToString()
feature/random-feature-for-sprint-1|94676d870a254642ec0c4511277ba6a289529b94|03dc87c944ed9f963e789eb009e5b1a2eb711cd4|2024-01-10 16:30:27 +0000|commit
```

```
$b0.BranchName
feature/random-feature-for-sprint-1|94676d870a254642ec0c4511277ba6a289529b94|03dc87c944ed9f963e789eb009e5b1a2eb711cd4|2024-01-10 16:30:27 +0000|commit
```

```
$b0.CommitDate
InvalidOperation: Method invocation failed because [git.branch] does not contain a method named 'CommitDate'.
```

Oh, I should mention, this operation fails because the branch object name is considered to be `feature/random-feature-for-sprint-1|94676d870a254642ec0c4511277ba6a289529b94|03dc87c944ed9f963e789eb009e5b1a2eb711cd4|2024-01-10 16:30:27 +0000|commit` by ugit.

I'd like to add the following to `branch` :

* `CommitDate` 
* `Ref`
* `ParentRef`
* `BranchType`

**Comment by StartAutomating** [comment]
@fcbry thanks for the suggestion!

This one is might be a little tricky, since trying to parse `--format` can interfere user intent (that is, if you wanted it formatted, you want it as a special form of text, not an object).

It could be possible to add some script properties to the git branch, that run an additional command, though if --format is the only way to get the data out, the same problem presents itself.

Truly, thanks for bringing this up, I'll see if I can come up with a way to pass the data thru, so that we can have our cake and eat it, too.

**Comment by StartAutomating** [comment]
@fcbry upon further thought and investigation, it appears something is wrong, and there is a creative workaround:

### What's Wrong

* #237

This is why the "BranchName" is so mangled.

Once this _stops_ handling --format, we're more free to handle it some other ways:

* #238
* #239

Please let me know what you think of this approach

**Comment by fcbry** [comment]
Sounds good, just one thing, you might want to allow the user to specify the delimiter, the reason I say this is that I realized in certain situations, it might be possible to manipulate things by adding the delimiter to the say the commit message or the branch name, the way I got around this was to use a long delimiter which is difficult to guess, in my case I took the date and applied a SHA operation to it, so for a particular run I'd use for example `~aef4445cde7~` as the delimiter, I supply a fresh delimiter every time I run git log or git branch now in my codebase.
