### ISSUE TITLE
Does not play well with posh-git

### ISSUE THREAD

**Issue by corbob** [StartAutomating/ugit#64]
<img width="1611" alt="2022-07-06_20-55-20" src="https://user-images.githubusercontent.com/30301021/177687337-2513542d-ae1b-4070-9152-2786ed082985.png">

I don't currently have any more information, but I can provide more if needed.

**Comment by StartAutomating** [comment]
* [x] [Opened issue in posh-git to track this](https://github.com/dahlbyk/posh-git/issues/912)
* [x] [Filed a pull request to posh-git to fix it](https://github.com/dahlbyk/posh-git/pull/913)

**Comment by StartAutomating** [comment]
Closing this issue upon integration of things into posh-git.  Will reopen if new things show up.
